name: Checks
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name : install dependancies
        run: sudo apt-get install ocl-icd-opencl-dev
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Format.
        run: make format
      - name: Linting & vetting.
        run: make lint
  Testing_and_building:
    runs-on: ubuntu-latest
    steps:
      - name : install dependancies
        run: sudo apt-get install ocl-icd-opencl-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all tags as well.
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Running tests
        run: make test
        env:
          VIXEOD_KEY: ${{ secrets.VIXEOD_KEY }}

      - name: Check generated files # Ensure that they are up to date.
        run: make generate-check

      - name: Building
        run: make build
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - name : install dependancies
        run: sudo apt-get install ocl-icd-opencl-dev
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Calc coverage
        env:
          GOTEST_OPTS: "-covermode=count -coverprofile=coverage.out"
          VIXEOD_KEY: ${{ secrets.VIXEOD_KEY }}
        run: make test
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.4
        with:
            infile: coverage.out
            outfile: coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
            github-token: ${{ secrets.github_token }}
            path-to-lcov: coverage.lcov
